### ISSUE TITLE
Failed to initialize PowerShell Tools for Visual Studio.System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by timabell** [adamdriscoll/poshtools#205]
Hello, thanks for the addon. I can't get it to load in Visual Studio 2013 on Win 7 x64. I installed the powershell 3 package as instructed and now get the following error when starting visual studio:

	---------------------------
	PowerShell Tools for Visual Studio Error
	---------------------------
	Failed to initialize PowerShell Tools for Visual
	Studio.System.Reflection.TargetInvocationException: Exception has been thrown
	by the target of an invocation. --->
	System.ComponentModel.Composition.ImportCardinalityMismatchException: No
	exports were found that match the constraint: 
		ContractName	PowerShellTools.VisualStudioEvents
		RequiredTypeIdentity	PowerShellTools.VisualStudioEvents
	   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
	   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality)
	   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String contractName, ImportCardinality cardinality)
	   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T](String contractName)
	   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T]()
	   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
	   at PowerShellTools.Diagnostics.DiagnosticsDialogPage..ctor()
	   --- End of inner exception stack trace ---
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
	   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)
	   at PowerShellTools.PowerShellToolsPackage.InitializeInternal()
	   at PowerShellTools.PowerShellToolsPackage.Initialize()
	---------------------------
	OK   
	---------------------------

which means very little to me I'm afraid. Let me know if I can supply any other details that might help.

**Comment by AndreSayreMSFT** [comment]
Hi @timabell !  Are you still getting this error on (latest)[http://aka.ms/get-poshTools] nightly builds?  and/or Do you have the latest update to Visual Studio 2013 installed?

**Comment by timabell** [comment]
yep that works, thanks, do you know when that's going to be released to the gallery?

**Comment by AndreSayreMSFT** [comment]
@timabell Officially, nope.  But we're working with @adamdriscoll on Coordinating for some events coming up.  Stay tuned :)

[Closing this out as issue has been fixed]

**Comment by cetama** [comment]
@AndreSayreMSFT: Sorry to say but I have the same issue with the latest nightly (3.0.134). I am also running 2013 on a Windows 7 64Bit. My PSVersionTable output is as follows: 

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2


The stack trace is:

---------------------------
PowerShell Tools for Visual Studio Error
---------------------------
Failed to initialize PowerShell Tools for Visual StudioSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Composition.ImportCardinalityMismatchException: No exports were found that match the constraint: 
	ContractName	PowerShellTools.VisualStudioEvents
	RequiredTypeIdentity	PowerShellTools.VisualStudioEvents

   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)

   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality)

   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String contractName, ImportCardinality cardinality)

   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T](String contractName)

   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[T]()

   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()

   at PowerShellTools.Diagnostics.DiagnosticsDialogPage..ctor()

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.VisualStudio.Shell.Package.GetDialogPage(Type dialogPageType)

   at PowerShellTools.PowerShellToolsPackage.InitializeInternal()

   at PowerShellTools.PowerShellToolsPackage.Initialize()
---------------------------
OK   
---------------------------

**Comment by dls314159** [comment]
@cetama 
I saw the problem with the most recent nightly here, but it was fixed in the MSFT fork of the project with the artifacts here: https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/build/artifacts

**Comment by AndreSayreMSFT** [comment]
@timabell @cetama @dls314159 [dlsπ] 

I'm reopening this issue, as while it was noted that it wasn't reproing anymore, given that it was reported again on the latest released build, took some time to look into it.

It is a bonafied bug/race-condition that needs to be fixed!  However, reinstalling often has the sideeffect of 'fixing' it when it rebuilds the MEF Cache-- Funkiness with regards to the MEF Export / Manual Import around the DiagnosticsDialogPage/VisualStudioEvents [misnomer, we shouldn't call it 'visual studio events :)]

We can refactor this page a bit; following the pattern around the 'GeneralDialogPage' to make things simple.

**Comment by ChrisVinall** [comment]
I encountered this as well. An uninstall/reinstall fixed it first time for me.

**Comment by burnchar** [comment]
I installed PowerShell Tools through "Extensions and Updates" a moment ago.
I too see ImportCardinalityMismatchException.
A reinstall fixed the issue.
