### ISSUE TITLE
Hitting 'tab' for IntelliSense match in Interactive window while IntelliSense is busy will cause an exception

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#223]
When trying to use tab completion while in the Interactive Window, I am continually seeing this:
```
---------------------------
Microsoft Visual Studio
---------------------------
Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index
---------------------------
OK   
---------------------------
```

I enabled diagnostics and saw this:
```
12:44:16,710 - 61 - PowerShellTools.ServiceManagement.PowershellHostProcessHelper - DEBUG - [009091ed-dec8-4b95-b2df-913efa954b8f]:Callback intellisense at position 27
12:44:16,710 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Finishing process intellisense completion list!
12:44:16,569 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - IsFilterTrigger: [\]
12:44:16,757 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Got new intellisense completion list
12:44:16,757 - 59 - PowerShellTools.Classification.PowerShellTokenizationService - DEBUG - Matching braces and regions.
12:44:16,757 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Failed to process completion results. Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at PowerShellTools.Intellisense.IntelliSenseManager.<>c__DisplayClass5.<IntelliSenseManager_CompletionListUpdated>b__3()
12:44:16,788 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Got new intellisense completion list
12:44:16,788 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Failed to process completion results. Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at PowerShellTools.Intellisense.IntelliSenseManager.<>c__DisplayClass5.<IntelliSenseManager_CompletionListUpdated>b__3()
```

This reproduces constantly.

It seems to happen when I hit "tab" while it's busy trying to resolve Intellisense items -- for instance I'm in a directory with dozens of items and I hit tab while it's still busy.

**Comment by AndreSayreMSFT** [comment]
Hi @theficus ! 

This seems to be related to Microsoft#449 -- Would you like to try our nightly build at http://aka.ms/get-poshtoolsNightly to see if that fixes your issue?

@EricJizbaMSFT

**Comment by AndreSayreMSFT** [comment]
Hi @theficus !  We think we've fixed this per above, but definitely let us know and reopen if you still see this!
