### ISSUE TITLE
IntelliSense not working

### ISSUE THREAD

**Issue by brettjacobson** [adamdriscoll/poshtools#272]
Previously i was severely affected by https://github.com/adamdriscoll/poshtools/issues/245  , but at least with this latest release on the 20th, i dont have popup windows, i just have no Intellisense.

here are some lines from teh debug output that may be relevant:
07:32:01,510 - 1 - PowerShellTools.Classification.PowerShellOutliningTagger - DEBUG - Updating with new tag spans.
07:32:01,746 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Non-VSStd2K command: 'CommandGroup: ffe1131c-8ea1-4d05-9728-34ad4611bda9, Id: 6155'
07:32:01,746 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Non-VSStd2K command: 'CommandGroup: 5efc7975-14bc-11cf-9b2b-00aa00573819, Id: 684'
07:32:01,746 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Non-VSStd2K command: 'CommandGroup: 1496a755-94de-11d0-8c3f-00c04fc2aae2, Id: 1990'
07:32:01,824 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Typed Character: '-'
07:32:01,824 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - IsIntelliSenseTriggerInStringLiteral: [-]
07:32:01,824 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - IsIntelliSenseTriggerDot: [-]
07:32:01,824 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - IsIntellisenseTrigger: [-]
07:32:01,824 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - IsFilterTrigger: [-]
07:32:01,824 - 11 - PowerShellTools.Classification.PowerShellTokenizationService - DEBUG - Parsing input.
07:32:01,840 - 1 - PowerShellTools.Classification.PowerShellOutliningTagger - DEBUG - GetTags
07:32:01,840 - 1 - PowerShellTools.Classification.PowerShellOutliningTagger - DEBUG - Returning existing tag spans.
07:32:01,840 - 11 - PowerShellTools.Classification.PowerShellTokenizationService - DEBUG - Classifying tokens.
07:32:01,840 - 11 - PowerShellTools.Classification.PowerShellTokenizationService - DEBUG - Tagging error spans.
07:32:01,840 - 11 - PowerShellTools.Classification.PowerShellTokenizationService - DEBUG - Matching braces and regions.
07:32:01,855 - 11 - PowerShellTools.Classification.PowerShellOutliningTagger - DEBUG - OnTagsChanged
07:32:01,918 - 1 - PowerShellTools.Classification.PowerShellOutliningTagger - DEBUG - GetTags
07:32:01,918 - 1 - PowerShellTools.Classification.PowerShellOutliningTagger - DEBUG - Updating with new tag spans.
07:32:02,027 - 61 - PowerShellTools.PowerShellToolsPackage - ERROR - Connection establish failed...
07:32:02,027 - 61 - PowerShellTools.Intellisense.IntelliSenseManager - WARN - Failed to start IntelliSense

**Comment by adamdriscoll** [comment]
@AndreSayreMSFT  @HuanhuanSunMSFT  Do you guys have any ideas?

**Comment by jinglou-** [comment]
@HuanhuanSunMSFT. could you please investigate for July?  Thanks.

**Comment by brettjacobson** [comment]
Just updating that v3.0.163 (latest version) still exhibits same problem in both VS2013 and VS2015.  Is the issue still being looked into?

**Comment by brettjacobson** [comment]
Is there any chance this is related to a similar Nuget issue?
https://github.com/NuGet/Home/issues/974

**Comment by HuanhuanSunMSFT** [comment]
Hi @brettjacobson, after you open a PowerShell script, can you check if there are two processes named ***PowerShellTools Host Service*** and ***PowerShellTools Host Service Console***, respectively, in your Task Manager.

**Comment by HuanhuanSunMSFT** [comment]
@brettjacobson, from the log you provided I assume you cannot see those two processes. As I cannot repro this on my machines, I have to ask for a favor. Can you try this [build](https://ci.appveyor.com/project/PoshTools-MSFT/poshtools/build/3.0.1398) and send us the logs? Thanks.

**Comment by brettjacobson** [comment]
@HuanhuanSunMSFT, here is an exception from the output window:
```
08:26:29,129 - 10 - PowerShellTools.PowerShellToolsPackage - INFO - InitializePowerShellHost
08:26:29,145 - 1 - PowerShellTools.Intellisense.IntelliSenseManager - DEBUG - Non-VSStd2K command: 'CommandGroup: ffe1131c-8ea1-4d05-9728-34ad4611bda9, Id: 6155'
08:26:30,020 - 46 - PowerShellTools.ServiceManagement.PowershellHostProcessHelper - DEBUG - [4b9a8e31-7def-431d-aff8-b819225251f3]:Creating and Attaching a console into pshost!
08:26:30,270 - 10 - PowerShellTools.PowerShellToolsPackage - ERROR - Connection establish failed... Error message: System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at net.pipe://localhost/4b9a8e31-7def-431d-aff8-b819225251f3/NamedPipePowershellDebugging that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.

Server stack trace: 
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.DecodeFramingFault(ClientFramingDecoder decoder, IConnection connection, Uri via, String contentType, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at PowerShellTools.Common.ServiceManagement.DebuggingContract.IPowerShellDebuggingService.SetRunspace(Boolean overrideExecutionPolicy)
```

Our company has pretty tight security on our machines; I believe this is the exact same problem that I experience with VS Test Discovery, mentioned here (unknown what is preventing the named pipes from working but most likely its some piece of security software IT installs): https://connect.microsoft.com/VisualStudio/feedback/details/807771/visual-studio-2013-test-explorer-only-works-if-run-as-administrator

I can confirm that if I run Visual Studio as Administrator, that PoSH Intellisense works as expected.  Unfortunately, doing that all the time is not an option.

**Comment by HuanhuanSunMSFT** [comment]
@brettjacobson Thanks for providing the log. Looks like so. To avoid any latency, we don't add any encryption for the named pipe binding. You can check out the code [here]( https://github.com/adamdriscoll/poshtools/blob/dev/PowerShellTools.HostService/App.xaml.cs).
```
binding.Security.Transport.ProtectionLevel = ProtectionLevel.None;
```
 Not sure whether it's the reason that the named pipe doesn't work out on your machine.

**Comment by brettjacobson** [comment]
Still doesn't work in latest release from yesterday.  Is this issue being abandoned??
Does no other company in the world operate with similar security policies that my company has that prevents this from working?
Is running as Administrator the only solution (that would seem bad)?

**Comment by iainbrighton** [comment]
For what it's worth - I don't receive any Intellisense running as Administrator or not! Running VS 2013 Community Update 5 and PoshTools build 3.0.177. I also do not see _PowerShellTools Host Service_ and/or a _PowerShellTools Host Service Console_ process(es), which presumably is the cause of my problems?

**Comment by Dean144** [comment]
I have 3.0.177 with  VS 2013 Update 5, Intellisense has worked a few times but most of the time it just shows Running Intellisense at the bottom of the screen

**Comment by brettjacobson** [comment]
FYI with the latest release, the enterprise security software (Bit9) is preventing it from running the .exe completely due to security policy.  I've requested they whitelist this, and will report back if the latest version fixes my intellisense problems once IT clears it.

**Comment by adamdriscoll** [comment]
That's interesting. I used a new certificate for this build so I could sign with SHA-256. Likely the issue.

**Comment by brettjacobson** [comment]
IT finally just disabled the Bit9 software on my machine, but it still does not work. Still no Intellisense, so I suspect its a group policy or something else thats blocking the .exe still
