### ISSUE TITLE
Using "Run All Tests" stalls without running any tests

### ISSUE THREAD

**Issue by PlagueHO** [adamdriscoll/poshtools#320]
In Visual Studio 2015, Clicking Run All Tests from Test Explorer or from the Tests menu with a project using the POSHTools extension shows the message:
*------ Run test started ------*
**The Test Explorer shows an activity progress bar moving, but none of the tests are run. The tests will run indefinitely without progressing or running a single test.**

Screenshot showing stalled Run All Tests:
![Screenshot](https://dscottraynsford.files.wordpress.com/2015/08/ss_poshtools_runalltests_stall.png)

**Selecting one or more tests in the Test Explorer window and clicking Run Selected Tests will run all tests. Using Invoke-Pester runs the tests correctly.**

This is using 3.0.177 of the POSHTools extension in Visual Studio 2015 on Windows 10.

**Comment by adamdriscoll** [comment]
Can you try installing this version and grabbing a log? https://ci.appveyor.com/project/adamdriscoll/poshtools/build/job/32o9dn2ce49vyiop/artifacts

https://github.com/adamdriscoll/poshtools/wiki/Debugging-PowerShell-Tools-for-Visual-Studio

**Comment by PlagueHO** [comment]
The same issue occurs, but here is the output of the log:
2015-10-08 14:10:41,491 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - SetExecutionPolicy(RemoteSigned,Process)
2015-10-08 14:10:42,601 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - Current Policy: Unrestricted
2015-10-08 14:10:42,686 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabConfiguration in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,689 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Test-LabConfiguration in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,691 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Install-LabHyperV in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,694 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabConfiguration in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,696 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabSwitches in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,698 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabSwitches in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,700 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Remove-LabSwitches in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,702 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabVMTemplates in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,704 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabVMTemplates in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,707 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Remove-LabVMTemplates in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,709 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Set-LabDSCMOFFile in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,711 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Set-LabDSCStartFile in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,713 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabUnattendFile in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,716 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Set-LabVMInitializationFiles in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,719 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabVMs in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,721 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabVMSelfSignedCert in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,724 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Start-LabVM in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,726 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabVMs in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,728 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Remove-LabVMs in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,731 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Wait-LabVMInit in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,733 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Wait-LabVMStart in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,735 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Wait-LabVMOff in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,738 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Install-Lab in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,740 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Uninstall-Lab in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:10:42,746 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - SetExecutionPolicy(RemoteSigned,Process)
2015-10-08 14:10:42,949 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - Current Policy: RemoteSigned
2015-10-08 14:10:44,358 [9] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - Running test: Get-LabConfiguration @ C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1

It does not proceed past this point. I can **cancel** the tests at this point. If I just right click the first test and select **run selected** I get the following log output:
2015-10-08 14:13:41,946 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabConfiguration in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,950 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Test-LabConfiguration in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,953 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Install-LabHyperV in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,956 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabConfiguration in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,962 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabSwitches in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,965 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabSwitches in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,968 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Remove-LabSwitches in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,970 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabVMTemplates in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,973 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabVMTemplates in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,976 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Remove-LabVMTemplates in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,978 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Set-LabDSCMOFFile in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,981 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Set-LabDSCStartFile in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,983 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabUnattendFile in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,986 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Set-LabVMInitializationFiles in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,988 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabVMs in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,991 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Get-LabVMSelfSignedCert in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:41,994 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Start-LabVM in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,004 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Initialize-LabVMs in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,006 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Remove-LabVMs in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,009 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Wait-LabVMInit in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,012 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Wait-LabVMStart in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,015 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Wait-LabVMOff in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,018 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Install-Lab in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,020 [19] DEBUG PowerShellTools.TestAdapter.PowerShellTestDiscoverer [(null)] - Found describe Uninstall-Lab in source C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1 at 1 with tags 
2015-10-08 14:13:42,409 [6] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - SetExecutionPolicy(RemoteSigned,Process)
2015-10-08 14:13:42,820 [6] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - Current Policy: Unrestricted
2015-10-08 14:13:43,559 [6] DEBUG PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - Running test: Get-LabConfiguration @ C:\Users\Daniel\Source\GitHub\LabBuilder\LabBuilder\LabBuilder.tests.ps1
2015-10-08 14:13:44,655 [6] WARN  PowerShellTools.TestAdapter.PowerShellTestExecutor [(null)] - Test run threw an exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PowerShellTools.TestAdapter.PowerShellTestExecutor.RunTest(PowerShell powerShell, TestCase testCase, IRunContext runContext)
   at PowerShellTools.TestAdapter.PowerShellTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)

I get the above System.NullReferenceException error no matter which test I run. This error isn't thrown by the Pester tests as far as I can tell.

HTH. Thanks!

**Comment by adamdriscoll** [comment]
Just realized there was a pretty big gap in the error handling in the test runner. Can you try this build? It may not fix the issue but should give us more info. 

https://ci.appveyor.com/project/adamdriscoll/poshtools/branch/dev/job/okh0jqicwicwiu4i/artifacts

**Comment by PlagueHO** [comment]
Hi Adam,

Thanks for that. I tried this version (had to uninstall the old one manually first because VS reported this version was already installed).

It has now stopped logging information from the PowerShellTools.TestAdapter completely. I confirmed the **Enable Diagnostic Logging** is enabled. Information is still being logged correctly from the other components of the extension:

2015-10-09 09:15:32,590 [1] DEBUG PowerShellTools.Classification.PowerShellTokenizationService [(null)] - Matching braces and regions.
2015-10-09 09:15:32,825 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 5efc7975-14bc-11cf-9b2b-00aa00573819, Id: 684'
2015-10-09 09:15:32,825 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 1496a755-94de-11d0-8c3f-00c04fc2aae2, Id: 1990'
2015-10-09 09:15:32,856 [1] DEBUG PowerShellTools.Classification.PowerShellOutliningTagger [(null)] - GetTags
2015-10-09 09:15:32,856 [1] DEBUG PowerShellTools.Classification.PowerShellOutliningTagger [(null)] - Updating with new tag spans.
2015-10-09 09:15:35,653 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 5efc7975-14bc-11cf-9b2b-00aa00573819, Id: 684'
2015-10-09 09:15:35,669 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 1496a755-94de-11d0-8c3f-00c04fc2aae2, Id: 1990'
2015-10-09 09:15:40,200 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 5efc7975-14bc-11cf-9b2b-00aa00573819, Id: 684'
2015-10-09 09:15:40,200 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 1496a755-94de-11d0-8c3f-00c04fc2aae2, Id: 1990'
2015-10-09 09:15:41,231 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 5efc7975-14bc-11cf-9b2b-00aa00573819, Id: 684'
2015-10-09 09:15:41,231 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 1496a755-94de-11d0-8c3f-00c04fc2aae2, Id: 1990'
2015-10-09 09:15:49,785 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 5efc7975-14bc-11cf-9b2b-00aa00573819, Id: 684'
2015-10-09 09:15:49,789 [1] DEBUG PowerShellTools.Intellisense.IntelliSenseManager [(null)] - Non-VSStd2K command: 'CommandGroup: 1496a755-94de-11d0-8c3f-00c04fc2aae2, Id: 1990'
2015-10-09 09:22:45,083 [1] INFO  PowerShellTools.Diagnostics.DiagnosticConfiguration [(null)] - Diagnostics enabled.

If I try to run the any tests (by right clicking and selecting run selected tests) I get the same error as before:
![2015-10-09_9-24-24](https://cloud.githubusercontent.com/assets/7589164/10378829/aab9b592-6e67-11e5-853a-1d4ca991570c.png)

I'm happy to try anything else you need.

Thanks
