### ISSUE TITLE
Does not install on Visual Studio Express 2013

### ISSUE THREAD

**Issue by marcoesch** [adamdriscoll/poshtools#428]
Does not install on Visual Studio Express 2013.
I tried both by download and the Gallery doesn't find it.
Would be very nice to support it ;-)
Here is the end of the log:
...
2016-03-08 17:01:58 - 	Supported Products : 
2016-03-08 17:01:58 - 		Microsoft.VisualStudio.IntegratedShell
2016-03-08 17:01:58 - 			Version : [12.0]
2016-03-08 17:01:58 - 		Microsoft.VisualStudio.Pro
2016-03-08 17:01:58 - 			Version : [12.0]
2016-03-08 17:01:58 - 
2016-03-08 17:01:58 - 	References      : 
2016-03-08 17:01:58 - 		-------------------------------------------------------
2016-03-08 17:01:58 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
2016-03-08 17:01:58 - 		Name         : Visual Studio MPF 11.0
2016-03-08 17:01:58 - 		Version      : [11.0]
2016-03-08 17:01:58 - 		MoreInfoURL  : 
2016-03-08 17:01:58 - 		Nested       : No
2016-03-08 17:01:58 - 
2016-03-08 17:01:58 - 
2016-03-08 17:01:58 - Searching for applicable products...
2016-03-08 17:02:00 - Found installed product - Microsoft Visual Studio Express 2013 for Windows Desktop
2016-03-08 17:02:00 - Found installed product - Global Location
2016-03-08 17:02:00 - Found installed product - ssms
2016-03-08 17:02:00 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by flcdrg** [comment]
Express does not support installing extensions. Are you able to use VS Community?
