### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by sedotakj** [adamdriscoll/poshtools#435]
Trying to install latest onto VS2015 update 2 and after fresh reboot. VS2015 is NOT running.
VSIX installer the message 
![image](https://cloud.githubusercontent.com/assets/12435173/14962638/78349ab0-1065-11e6-8258-424c799fa5dd.png)
Not sure what I am supposed to stop.

Errors from log:
5/2/2016 12:57:13 PM - Beginning to install extension to Microsoft Visual Studio Professional 2015...
5/2/2016 12:57:13 PM - Upgrading 'PowerShell Tools for Visual Studio 2015', version 3.0.299 to version 3.0.375.
5/2/2016 12:57:13 PM - Install Error : System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.AtomicallyDeleteFiles(IEnumerable`1 filePaths, Boolean justMarkForDeletion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.DeleteDiscoverableFiles(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UninstallInternal(IInstalledExtension extension, Boolean forceDelete)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
##

**Comment by adamdriscoll** [comment]
Can you upload the install log?

**Comment by sedotakj** [comment]
quick on the draw!. Updated original post.

**Comment by sedotakj** [comment]
[VSIXInstaller_700f20da-f029-4978-90ce-149f03b36a60.txt](https://github.com/adamdriscoll/poshtools/files/245632/VSIXInstaller_700f20da-f029-4978-90ce-149f03b36a60.txt)

**Comment by ahearnstl** [comment]
Look in Task Manager and make sure that you do not have some VS process hanging in there.  From the error logs, it looks like VS did not close cleanly - i.e. part of it is still running.

**Comment by sedotakj** [comment]
The only thing I see running is C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools
and this keeps restarting each time I stop it. I don't knwo why and I don't know if it's related

**Comment by ahearnstl** [comment]
I don't have much experience with TFS, so I'm not sure.  you could try manually removing the old poshtools files and then re-running the install.  Beyond that, I'm at a loss.

**Comment by adamdriscoll** [comment]
That may be a result of the windows explorer integration for those PowerTools. Not sure if that's related. Try and uninstall\install of PoshTools to see if that works.

**Comment by sedotakj** [comment]
can not uninstall. I tried from VS2015 and also from command line vsixinstaller /u:59875F69-67B7-4A5C-B33A-9E2C2B5D266D

but got the same error:
5/2/2016 3:51:59 PM - Uninstalling 'PowerShell Tools for Visual Studio 2015', version 3.0.299.
5/2/2016 3:51:59 PM - System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.AtomicallyDeleteFiles(IEnumerable`1 filePaths, Boolean justMarkForDeletion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.DeleteDiscoverableFiles(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UninstallInternal(IInstalledExtension extension, Boolean forceDelete)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Uninstall(IInstalledExtension extension)
   at VSIXInstaller.App.UninstallExtensionFromSKU(String vsixID, SupportedVSSKU sku)

**Comment by adamdriscoll** [comment]
Can you run procmon while trying to uninstall, save the trace and upload it for review?

**Comment by sedotakj** [comment]
I have run procmon and have a log. I presume I should be filtering on VSIXInstaller.exe. I also filtered on CreateFile with Result != SUCCESS.
I see a SHARING VIOLATION on PowerShellTools.14.0.pkgdef in the extensions directory. 
Is there something else I need to look for. 
Alternately Are there specific filters you would like me to use?

**Comment by jdshkolnik** [comment]
7/19/2016 10:56:03 AM - Beginning to install extension to Microsoft Visual Studio Enterprise 2015...
7/19/2016 10:56:03 AM - Upgrading 'PowerShell Tools for Visual Studio 2015', version 3.0.375 to version 3.0.399.
7/19/2016 10:56:04 AM - Install Error : System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.AtomicallyDeleteFiles(IEnumerable`1 filePaths, Boolean justMarkForDeletion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.DeleteDiscoverableFiles(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UninstallInternal(IInstalledExtension extension, Boolean forceDelete)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)

**Comment by jdshkolnik** [comment]
I was only able to update by rebooting into safe mode.

**Comment by sedotakj** [comment]
I was eventually able to install it by remove each and every extension then starting over installing fresh. 
I suspect the extension had gotten installed multiple times and I just needed to clear them all out. 
Probably overkill but I couldn't seem to find all of the instances where it was installed. 
 
It's working now. 
 
--------- Original Message --------- Subject: Re: [adamdriscoll/poshtools] Install fails (#435)
