### ISSUE TITLE
Console shows tests actually passing, but Test Explorer shows all tests failing

### ISSUE THREAD

**Issue by jhandel** [adamdriscoll/poshtools#452]
When I run a test from the explorer I get the following type of error (doesn't matter which test I run)
```
Test Name:	ImpersonationTesting
Test FullName:	ImpersonationTesting
Test Source:	C:\projects\DevOpsTools\vsts-extention-tasks\TestLib\ImpersonationTesting.Tests.ps1 : line 3
Test Outcome:	Failed
Test Duration:	0:00:00

Result StackTrace:	
at PowerShellTools.TestAdapter.PowerShellTestExecutor.RunTest(PowerShell powerShell, TestCase testCase, IRunContext runContext)
   at PowerShellTools.TestAdapter.PowerShellTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
Result Message:	Object reference not set to an instance of an object.
```

But if look at the "Tests" console for that test it passed

```
------ Run test started ------
[VERBOSE] Dummy Import-Module
Describing ImpersonationTesting
   Context Exists
Hello world
    [+] Runs 1.05s
Tests completed in 1.05s
Passed: 1 Failed: 0 Skipped: 0 Pending: 0


========== Run test finished: 1 run (0:00:03.1930001) ==========
```

**Comment by jhandel** [comment]
Here is a sample test in question (it happens to all my tests though)
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$script = "$here\..\StartWindowsScheduledTasks\StartScheduleTasks.ps1"
Describe "ImpersonationTesting" {
	Context "Exists" {
		It "Runs" {
			Import-Module $script
			Invoke-ScriptBlockAsUser -adminUserName 'WFM\2067560' -adminPassword 'WholeFoods108HH$$' -scriptBlock {Write-Host 'Hello world'}
		}
	}
}
```

**Comment by adamdriscoll** [comment]
Can you test this again on the newest version? https://github.com/adamdriscoll/poshtools/releases/tag/v3.0.399

**Comment by jhandel** [comment]
Newest version does see to fix this..   Thanks..
