### ISSUE TITLE
Visix error when installing into VS 2017

### ISSUE THREAD

**Issue by kevinkuszyk** [adamdriscoll/poshtools#524]
I just downloaded the latest (3.0.539) extension from the market place.  I get the following error when trying to install into VS 2017:

![image](https://cloud.githubusercontent.com/assets/2734580/26412473/c8282ade-40a0-11e7-8807-9fe1d8dc2cd4.png)

I have the latest 2017.2 update:

![image](https://cloud.githubusercontent.com/assets/2734580/26412516/ee9526fe-40a0-11e7-84e0-c1156678b200.png)

This may be a dupe of #520.  Unfortunately I don't have VS 2015 to verify.

**Comment by adamdriscoll** [comment]
Is there a chance you can upload the VSIX? I just downloaded it from the Marketplace and it appears to be ok.

**Comment by adamdriscoll** [comment]
Also, can you try this again? I think something was wrong with the Marketplace a couple days ago.

**Comment by nickalleyne** [comment]
I had the same issue a couple weeks ago, but on Friday I was able to re-download and install.

**Comment by kevinkuszyk** [comment]
Ok, so I tried a fresh download today (from the UK) and I get the same error.  Here are zips of the VSIX from last week, and again today:
  
- [PowerShellTools.15.0 - last week.zip](https://github.com/adamdriscoll/poshtools/files/1037813/PowerShellTools.15.0.-.last.week.zip)
- [PowerShellTools.15.0 - today.zip](https://github.com/adamdriscoll/poshtools/files/1037812/PowerShellTools.15.0.-.today.zip)

**Comment by adamdriscoll** [comment]
@kevinkuszyk Thanks. I tried both of these and did not receive the same error you are seeing. Is the VSIX installer producing a VSIX log?

**Comment by kevinkuszyk** [comment]
@adamdriscoll indeed it is:

```
05/06/2017 17:01:17 - Microsoft Visual Studio Extension Installer
05/06/2017 17:01:17 - -------------------------------------------
05/06/2017 17:01:17 - Initializing Install...
05/06/2017 17:01:18 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: The extension manifest is invalid. ---> System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <PackageManifest xmlns='http://schemas.microsoft.com/developer/vsx-schema/2011'> was not expected.
   at Microsoft.VisualStudio.ExtensionManager.Implementation.XmlSerializationReaderVsix.Read12_Vsix()
   at Microsoft.VisualStudio.ExtensionManager.Implementation.VsixSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadVSIXManifest(Stream vsixManifestStream)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadVSIXManifest(Stream vsixManifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream vsixStream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.InitializeInstall()
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)
```

**Comment by adamdriscoll** [comment]
@kevinkuszyk I have no idea why this is happening. I'm going to reach out to MSFT to see if they can help.

**Comment by kevinkuszyk** [comment]
@adamdriscoll did you hear anything back from Microsoft on this?

**Comment by adamdriscoll** [comment]
@kevinkuszyk Sorry. No i didn't. I'll ask around the extendvs chat as well.

**Comment by adamdriscoll** [comment]
@kevinkuszyk Have you tried this on another machine or tried re-installing VS? I had someone suggest it may have to do with the VS install.

**Comment by kevinkuszyk** [comment]
Ok, it's very odd.  On a new Azure VM in VS pre-installed I can download it from the market place and it installs.

On my machine the latest download from the market place still doesn't open with the error above.  However - it just installed fine from downloading via the extensions and updates window in VS.

I have no idea what that means.  Feel free to close and chalk it up as a quirk on my machine if you want.
