### ISSUE TITLE
UniversalDashboard - Method Not Found 

### ISSUE THREAD

**Issue by sheldonhull** [adamdriscoll/poshtools#574]
I've tried this basic command and am getting method not found. Can't get more detail to show up to figure out what might be causing this. Any ideas? 
On version 1.0.265

stack trace
```
ErrorRecord                 : Method not found: 'Void NLog.Logger.Error(System.Exception, System.String)'.
WasThrownFromThrowStatement : False
Message                     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method not found: 'Void NLog.Logger.Error(System.Exception, 
                              System.String)'.
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : 
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                              --- End of stack trace from previous location where exception was thrown ---
                                 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                 at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                 at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
HelpLink                    : 
Source                      : mscorlib
HResult                     : -2146233087

```

Sample script 

```
[string[]]$HeaderList = @(
     'CreatingProcessID'
     ,'Name'
     ,'ElapsedTime'
     ,'PercentProcessorTime'
     ,'PercentUserTime'
     ,'PercentPrivilegedTime'
     ,'IODataOperationsPerSec'
     ,'IOReadOperationsPerSec'
     ,'IOWriteOperationsPerSec'
     ,'IOReadBytesPerSec'
     ,'IOWriteBytesPerSec'
     ,'PrivateBytes'
)
  

New-UDDashboard -Title 'Sizing Tests' -Content { 
     New-UDTable -Title 'Completed Tests' -Headers $HeaderList -verbose:$true -Endpoint {
          [pscustomobject[]]$result =    @(Get-WmiObject Win32_PerfFormattedData_PerfProc_Process -Filter "PercentProcessorTime > 0 and not Name = '_Total' and not Name = 'Idle'").Foreach({
                    [pscustomobject]@{
                         CreatingProcessID       = $_.CreatingProcessID
                         Name                    = $_.Name.Replace(' ', '\ ').Replace(',', '\,').Replace('=', '\=')
                         ElapsedTime             = $_.ElapsedTime
                         PercentProcessorTime    = ($_.PercentProcessorTime     ) / $vPhysicalCPUs
                         PercentUserTime         = ($_.PercentUserTime          ) / $vPhysicalCPUs
                         PercentPrivilegedTime   = ($_.PercentPrivilegedTime    ) / $vPhysicalCPUs
                         IODataOperationsPerSec  = $_.IODataOperationsPerSec
                         IOReadOperationsPerSec  = $_.IOReadOperationsPerSec
                         IOWriteOperationsPerSec = $_.IOWriteOperationsPerSec
                         IOReadBytesPerSec       = $_.IOReadBytesPerSec
                         IOWriteBytesPerSec      = $_.IOWriteBytesPerSec
                    PrivateBytes            = $_.PrivateBytes                                          }

          }) 
          $result |  Out-UDTableData -Property $HeaderList
     } 
}
```

**Comment by sheldonhull** [comment]
The examples are still unusable for me due to this error. Here's another example with the latest 1.0.271

          
```
Start-UDDashboard -content {
     New-UDDashboard -Color "blue" -Content {
          New-UDGrid -Title "Process Ids" -Headers  @("Name", "Id") -Properties  @("Name", "Id") -Endpoint {
               Get-Process -Name Chrome | Out-UDTableData -Property @("name", "id")
          }
     }
}
```

**Comment by adamdriscoll** [comment]
Tracking in the pro tools repo.
