### ISSUE TITLE
CRITICAL: Reverting to version 3.0.552 from 3.0.585 breaks VS Installer

### ISSUE THREAD

**Issue by yurikus** [adamdriscoll/poshtools#586]
VS2017 15.5 fails to repar, modify, or operate on extentions: Microsoft.Net.4.6.FullRedist,version=4.6.0.0 missing.

> [2fdc:000c][2017-12-07T00:12:17] Error 0x80131500: The dependent package cannot be found: Microsoft.Net.4.6.FullRedist.NonThreshold,version=4.6.0.0
   at Microsoft.VisualStudio.Setup.Dependencies.DependencyManager.FindDependentPackages(Dependency dependency, DependencyComparer comparer, Dictionary`2 packageIndex)
   at Microsoft.VisualStudio.Setup.Dependencies.DependencyManager.BuildGraphRecursive(IPackage graphRoot, DependencyNode node, DependencyComparer comparer, Dictionary`2 packageIndex, Dictionary`2 nodeIndex, Boolean splitNodes)
   at Microsoft.VisualStudio.Setup.Dependencies.DependencyManager.BuildGraphRecursive(IPackage graphRoot, DependencyNode node, DependencyComparer comparer, Dictionary`2 packageIndex, Dictionary`2 nodeIndex, Boolean splitNodes)
   at Microsoft.VisualStudio.Setup.Dependencies.DependencyManager.BuildGraphRecursive(IPackage graphRoot, DependencyNode node, DependencyComparer comparer, Dictionary`2 packageIndex, Dictionary`2 nodeIndex, Boolean splitNodes)
   at Microsoft.VisualStudio.Setup.Dependencies.DependencyManager.BuildGraphRecursive(IPackage graphRoot, DependencyNode node, DependencyComparer comparer, Dictionary`2 packageIndex, Dictionary`2 nodeIndex, Boolean splitNodes)
   at Microsoft.VisualStudio.Setup.Dependencies.DependencyManager.BuildGraphCore(IPackage root, IEnumerable`1 packages, DependencyComparer comparer, Dictionary`2 packageIndex, Dictionary`2 nodeIndex, Boolean splitNodes, DependencyCollection deprecated)
   at Microsoft.VisualStudio.Setup.Dependencies.DependencyManager.BuildGraph(IPackage root, IEnumerable`1 packages, Boolean isUpdate, IDependencyComparisonSeed seed, DependencyCollection deprecated)
   at Microsoft.VisualStudio.Setup.Engine.GetDependencyGraph(Product product)
   at Microsoft.VisualStudio.Setup.Engine.TryBuildDependencyGraph(Product product, Exception& error, Boolean overwrite, ITelemetryOperation telemetryOperation)

See this bug report: https://developercommunity.visualstudio.com/content/problem/162638/vs2017-155-fails-to-repar-modify-or-operate-on-ext.html

**Comment by yurikus** [comment]
MS support came through with a workaround: (remove dependencies for the extension from _package.json.) https://developercommunity.visualstudio.com/content/problem/162638/vs2017-155-fails-to-repar-modify-or-operate-on-ext.html

**Comment by whiskeyjay** [comment]
The problem was caused by the fact that the in-box version of PoshTools uses a different component ID within the Visual Studio setup than the marketplace version of PoshTools.

I have made a change in the Visual Studio setup to use the same component ID as the marketplace version.

The fix should be available in the upcoming VS release.
