### ISSUE TITLE
Failed to install the tool for Visual studio 2015

### ISSUE THREAD

**Issue by Yasilagit** [adamdriscoll/poshtools#604]
2/12/2018 10:16:27 PM - Microsoft VSIX Installer
2/12/2018 10:16:27 PM - -------------------------------------------
2/12/2018 10:16:27 PM - vsixinstaller.exe version:
2/12/2018 10:16:27 PM - 15.5.99+g87f89a485e
2/12/2018 10:16:27 PM - -------------------------------------------
2/12/2018 10:16:27 PM - Command line parameters:
2/12/2018 10:16:27 PM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\yasilapichaih\Downloads\PowerShellTools.14.0.vsix,/callingprocessid:18868,/installas:3352
2/12/2018 10:16:27 PM - -------------------------------------------
2/12/2018 10:16:27 PM - Microsoft VSIX Installer
2/12/2018 10:16:27 PM - -------------------------------------------
2/12/2018 10:16:27 PM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\ssms.exe: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
2/12/2018 10:16:28 PM - Initializing Install...
2/12/2018 10:16:28 PM - Extension Details...
2/12/2018 10:16:28 PM - 	Identifier         : 59875F69-67B7-4A5C-B33A-9E2C2B5D266D
2/12/2018 10:16:28 PM - 	Name               : PowerShell Tools for Visual Studio 2015
2/12/2018 10:16:28 PM - 	Author             : Adam Driscoll
2/12/2018 10:16:28 PM - 	Version            : 3.1.618
2/12/2018 10:16:28 PM - 	Description        : A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.
2/12/2018 10:16:28 PM - 	Locale             : en-US
2/12/2018 10:16:28 PM - 	MoreInfoURL        : https://poshtools.com/
2/12/2018 10:16:28 PM - 	InstalledByMSI     : False
2/12/2018 10:16:28 PM - 	SupportedFrameworkVersionRange : [4.5,)
2/12/2018 10:16:28 PM - 
2/12/2018 10:16:28 PM - 	SignatureState     : ValidSignature
2/12/2018 10:16:28 PM - 	SignedBy           : Adam Driscoll
2/12/2018 10:16:28 PM - 	Certificate Info   : 
2/12/2018 10:16:28 PM - 		-------------------------------------------------------
2/12/2018 10:16:28 PM - 		[Subject]       : CN=Adam Driscoll, O=Adam Driscoll, L=Madison, S=WISCONSIN, C=US
2/12/2018 10:16:28 PM - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
2/12/2018 10:16:28 PM - 		[Serial Number] : 0EED5A31B9B97D35B115A1136C45C65C
2/12/2018 10:16:28 PM - 		[Not Before]    : 1/22/2018 8:00:00 AM
2/12/2018 10:16:28 PM - 		[Not After]     : 3/6/2019 8:00:00 PM
2/12/2018 10:16:28 PM - 		[Thumbprint]    : BE87B4BD86289EC9A27779D54D0DFFD369AE24C3
2/12/2018 10:16:28 PM - 
2/12/2018 10:16:28 PM - 	Supported Products : 
2/12/2018 10:16:28 PM - 		Microsoft.VisualStudio.IntegratedShell
2/12/2018 10:16:28 PM - 			Version : [14.0,15.0)
2/12/2018 10:16:28 PM - 		Microsoft.VisualStudio.Pro
2/12/2018 10:16:28 PM - 			Version : [14.0,15.0)
2/12/2018 10:16:28 PM - 
2/12/2018 10:16:28 PM - 	References         : 
2/12/2018 10:16:28 PM - 		-------------------------------------------------------
2/12/2018 10:16:28 PM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
2/12/2018 10:16:28 PM - 		Name         : Visual Studio MPF 11.0
2/12/2018 10:16:28 PM - 		Version      : [11.0]
2/12/2018 10:16:28 PM - 		MoreInfoURL  : 
2/12/2018 10:16:28 PM - 		Nested       : No
2/12/2018 10:16:28 PM - 
2/12/2018 10:16:28 PM - Signature Details...
2/12/2018 10:16:28 PM - 	Extension is signed with a valid signature.
2/12/2018 10:16:28 PM - 
2/12/2018 10:16:28 PM - Searching for applicable products...
2/12/2018 10:16:28 PM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
2/12/2018 10:16:28 PM - Found installed product - Microsoft Visual Studio Professional 2015
2/12/2018 10:16:28 PM - System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at VSIXInstaller.SettingsManager.CreateForApplication(String devenvPath, String rootSuffix, PkgDefManagementFlags flags, IntPtr userToken, IntPtr regRootHiveOverride)
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.App.GetExtensionEngineForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.App.TryAddSkuToValidSkuList(SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
2/12/2018 10:16:28 PM - Found installed product - Microsoft Visual Studio Community 2015
2/12/2018 10:16:28 PM - System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at VSIXInstaller.SettingsManager.CreateForApplication(String devenvPath, String rootSuffix, PkgDefManagementFlags flags, IntPtr userToken, IntPtr regRootHiveOverride)
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.App.GetExtensionEngineForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.App.TryAddSkuToValidSkuList(SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
2/12/2018 10:16:28 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
2/12/2018 10:16:29 PM - System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at VSIXInstaller.SettingsManager.CreateForApplication(String devenvPath, String rootSuffix, PkgDefManagementFlags flags, IntPtr userToken, IntPtr regRootHiveOverride)
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.App.GetExtensionEngineForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.App.TryAddSkuToValidSkuList(SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
2/12/2018 10:16:29 PM - Found installed product - Global Location
2/12/2018 10:16:29 PM - Found installed product - Visual Studio Community 2017
2/12/2018 10:16:29 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by adamdriscoll** [comment]
Is this a fresh install of Visual Studio and PoshTools?

**Comment by Yasilagit** [comment]
I have two versions of visual studio.

Vs2015
Vs2017

-Vs2015 was installed 6 months ago
-vs2017 was installed a month ago

Both the Powershell tool failed both the versions of vs.

Kindly help to resolve the issues.
