### ISSUE TITLE
No tests discovers with standalone vstest.console.exe

### ISSUE THREAD

**Issue by smadala** [adamdriscoll/poshtools#628]
- Create PowerShellTools test adapter test project.
- Run the tests with standalone vstest.console.exe which can be obtained from [Nuget.org](https://www.nuget.org/packages/Microsoft.TestPlatform/15.8.0-preview-20180605-02), Path to vstest.console.exe is `tools\net451\Common7\IDE\Extensions\TestPlatform`.

**Expected behavior**
- Test should get discovered and run.

**Actual behavior**
 
 ```
Microsoft (R) Test Execution Command Line Tool Version <vstest.console.exe version>
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
```

**Root cause**
- Failed to load Microsoft.VisualStudio.TestWindow.Interfaces assembly(See stacktrace below).

```
TpTrace Warning: 0 : 26264, 3, 2018/06/11, 16:17:52.997, 5640404771253, testhost.x86.exe, TestPluginDiscoverer: Failed to get types from assembly 'PowerShellTools.TestAdapter, Version=3.0.299.1, Culture=neutral, PublicKeyToken=32cd18849a3a99f8'.  Skipping test extension scan for this assembly.  Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos) in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginDiscoverer.cs:line 168
TpTrace Warning: 0 : 26264, 3, 2018/06/11, 16:17:52.997, 5640404773925, testhost.x86.exe, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestWindow.Interfaces, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args) in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginCache.cs:line 509
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver.AssemblyResolverEvent(Object sender, Object eventArgs) in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.PlatformAbstractions\net451\Runtime\PlatformAssemblyResolver.cs:line 74
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

```

**Proposed fix**
- Remove Microsoft.VisualStudio.TestWindow.Interfaces dependency for  GoogleTestAdapter.TestAdapter. Like [Chutzpah test adapter](https://www.nuget.org/packages/Chutzpah/) .
- `Microsoft.VisualStudio.TestWindow.Interfaces` contains API related to UI components(Test explorer). This assembly not ships with standalone vstest.console.exe.

**Additional data**
- [Microsoft.TestPlatform](https://www.nuget.org/packages/Microsoft.TestPlatform/15.8.0-preview-20180605-02) package used extensively in CI/CD pipeline(build agents without VS installed) both internally and external to Microsoft.
- This issue blocking us to on board some of teams to CloudBuild(Microsoft internal distributed build system)

**Comment by smadala** [comment]
@adamdriscoll Did you get chance to look at this?

**Comment by surthumm** [comment]
We are blocked on this as well. Could you please help fix this issue?

**Comment by adamdriscoll** [comment]
@smadala Apologies for the delay. I've been traveling for the last couple weeks. 

I don't have time to fix this at the moment but am happy to accept a PR that resolves this if you submit one. It looks like you have the fix nailed down.

**Comment by smadala** [comment]
@adamdriscoll I'm not sure I will get time to work on this next three weeks(Will be on vacation one week). It will be great if you can fix it before that 😄.

**Comment by surthumm** [comment]
Any update on this? This is open for more than a month. It would be great if you can help address this issue.

**Comment by surthumm** [comment]
Any update? Its been a while the issue is being reported.
